### ISSUE TITLE
IAudioClient::Initialize caused an error: 0x88890008, "Unknown HRESULT".

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [DarthAffe/KeyboardAudioVisualizer#27]
Keyboard : K70 RGB Rapidfire
OS: Windows 10 64 bits
``
[27/09/2018 20:30:01] Exception!

Message:
IAudioClient::Initialize caused an error: 0x88890008, "Unknown HRESULT".

StackTrace:
   à CSCore.SoundIn.WasapiCapture.InitializeInternal()
   à CSCore.SoundIn.WasapiCapture.Initialize()
   à KeyboardAudioVisualizer.AudioCapture.CSCoreAudioInput.Initialize()
   à KeyboardAudioVisualizer.AudioProcessing.AudioVisualizationFactory.InitializeInstance()
   à KeyboardAudioVisualizer.AudioProcessing.AudioVisualizationFactory.Initialize()
   à KeyboardAudioVisualizer.App.OnStartup(StartupEventArgs e)

``

![hbgrhbufrdyh](https://user-images.githubusercontent.com/29174751/46166767-4138f400-c294-11e8-96e6-73e4e3f90496.JPG)

**Comment by DarthAffe** [comment]
Hey, this issue is audio-driver related. 
The first thing was the usage of "fake"-7.1/5.1-devices (but this should be workarounded), the second is an issue with some audio settings (as described here https://github.com/filoe/cscore/issues/322). I can't really help you much aside from the recommendation of trying around with different settings on the loopback-device.

**Comment by TomAvecLeVdsl** [comment]
Like use a 2.1 device as master speaker?

**Comment by TomAvecLeVdsl** [comment]
So , I unistalled my audio driver and it works now :) Thanks for the help
